### ISSUE TITLE
Should have a contributing.md

### ISSUE THREAD

**Issue by hibooboo2** [rancher/cattle#145]
We currently have and implied and assumed process for contributing. We should create an md for all the repos / projects so that it is clear and consistent . Here are some base starting notes i went over with @cjellick 

* Fork the rancherio/cattle repo to your account.
* Clone your fork.
* Run tests locally off of your fork, make sure they pass.
* Branch to start a feature.
* Write Feature and Tests.
* Run tests and make sure they all pass.
* Push branch to your repo.
* Fetch latest changes from rancherio/cattle master and solve conflicts with your changes(if there are any).
* Run tests again
* Submit PR (Label it as WIP if that applies.)
* After Review before changes are merged Squash commits into meaningful commits. If only one that is fine.
* PR is merged.

**Comment by vincent99** [comment]
So that basically describes the standard basic github fork/pull request workflow.  Which is fine, but a CONTRIBUTING.md file is usually about a lot more than that.. So if we're going to create one it should be reasonable complete, with things like:
  - How to report bugs, request features, update documentation (not every contribution is code)
  - Reporting security issues out-of-band
  - Code formatting guidelines
  - Testing rules (is there a test for your change?)
  - How PR get approved and by whom
  - Contributor license agreement/Signed-Off-By
  - IRC channels to join
  - Code of conduct(probably not relevant for now)

**Comment by hibooboo2** [comment]
I agree all of that would be great to have.
