### ISSUE TITLE
Correct the inconsistent request/reply event data structure in AgentBasedProcessHandler

### ISSUE THREAD

**Issue by yasker** [rancher/cattle#161]
When AgentBasedProcessHander is sending a event out, it would contain the top level key, like:

InstanceHostMap: { Instance: { Volumes: { .. } .. }.. }

But currently when agent response with the reply event, the presumed data structure is:

Instance: { Volumes: { .. } .. } 

The reason is this data would be processed as key/value pairs in DefaultProcessInstanceImpl directly, as parameter to "state.applyData()", which would only work without the top level key, since it would apply the data to a known resource.

**Comment by ibuildthecloud** [comment]
As mentioned before this is low priority so please do not dedicate too much time to this.  Your example of modifying the request and replying is actually a bad one.  Because we have no mvcc style checks in place such a pattern can cause data inconsistencies in the DB.  The response should include only the fields that should change, not all of them.  Events can take minutes to be processed so that leave a huge windiw

**Comment by yasker** [comment]
@ibuildthecloud In fact I am already preparing pull request for it. Seems it's not that complex and integration test is passed.

**Comment by yasker** [comment]
@ibuildthecloud I've updated the comment to remove the transfer back the object part.

**Comment by ibuildthecloud** [comment]
Sorry, I accidentally closed this.
