### ISSUE TITLE
Projects: GET /v1/projects/:id for invalid IDs returns a random project

### ISSUE THREAD

**Issue by vincent99** [rancher/cattle#226]
GET /v1/projects/:id for an ID that doesn't belong to me, or even exist, returns a seemingly random project.  Possibly the last one that I do have access to?  But should be 404.

**Comment by ibuildthecloud** [comment]
@sidharthamani I just noticed that ProjectResourceManager is extending AbstractJooqResourceManager.  This is dangerous because that class has  A LOT of default behavior that is related to DB operations.  Since project is really a "virtual" type, you should extend AbstractNoOpResourceManager.  This provides no "default" behavior.

Please refer to `io.github.ibuildthecloud.gdapi.request.resource.impl.AbstractBaseResourceManager.getById(String, String, ListOptions)` and you'll see why /v1/projects/:id is not working.

**Comment by vincent99** [comment]
Obsolete
